<a href="https://colab.research.google.com/github/yoshuaSigala03/R_KMMI6/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [218]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [219]:
dataset = pd.read_csv('/content/Data1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [220]:
print(X)

[['Buku' nan 96000.0]
 ['Pensil' 25.0 nan]
 ['Pulpen' 10.0 57000.0]
 ['Pensil' nan 77070.0]
 ['Pulpen' 7.0 nan]
 ['Buku' 29.0 69300.0]
 ['Pensil' nan 191100.0]
 ['Buku' 37.0 89080.0]
 ['Pulpen' 10.0 57775.0]
 ['Buku' 7.0 38970.0]]


In [221]:
print(y)

['Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes']


In [222]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

print(X)

[['Buku' 17.857142857142858 96000.0]
 ['Pensil' 25.0 84536.875]
 ['Pulpen' 10.0 57000.0]
 ['Pensil' 17.857142857142858 77070.0]
 ['Pulpen' 7.0 84536.875]
 ['Buku' 29.0 69300.0]
 ['Pensil' 17.857142857142858 191100.0]
 ['Buku' 37.0 89080.0]
 ['Pulpen' 10.0 57775.0]
 ['Buku' 7.0 38970.0]]


In [223]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)


[[1.0 0.0 0.0 17.857142857142858 96000.0]
 [0.0 1.0 0.0 25.0 84536.875]
 [0.0 0.0 1.0 10.0 57000.0]
 [0.0 1.0 0.0 17.857142857142858 77070.0]
 [0.0 0.0 1.0 7.0 84536.875]
 [1.0 0.0 0.0 29.0 69300.0]
 [0.0 1.0 0.0 17.857142857142858 191100.0]
 [1.0 0.0 0.0 37.0 89080.0]
 [0.0 0.0 1.0 10.0 57775.0]
 [1.0 0.0 0.0 7.0 38970.0]]


In [224]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

print(y)

[1 1 0 0 1 0 0 1 0 1]


In [225]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [226]:
print(X_train)


[[0.0 1.0 0.0 17.857142857142858 191100.0]
 [0.0 0.0 1.0 7.0 84536.875]
 [1.0 0.0 0.0 17.857142857142858 96000.0]
 [0.0 1.0 0.0 17.857142857142858 77070.0]
 [0.0 1.0 0.0 25.0 84536.875]
 [1.0 0.0 0.0 37.0 89080.0]
 [0.0 0.0 1.0 10.0 57775.0]
 [1.0 0.0 0.0 29.0 69300.0]]


In [227]:
print(X_test)

[[0.0 0.0 1.0 10.0 57000.0]
 [1.0 0.0 0.0 7.0 38970.0]]


In [228]:
print(y_train)

[0 1 1 0 1 1 0 0]


In [229]:
print(y_test)

[0 1]


In [230]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [231]:
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [232]:
print(X_train)

[[0.0 1.0 0.0 -0.2542050897677476 2.5320360396666306]
 [0.0 0.0 1.0 -1.4340271857890505 -0.23749170229683292]
 [1.0 0.0 0.0 -0.2542050897677476 0.06042976628899288]
 [0.0 1.0 0.0 -0.2542050897677476 -0.43155242882182393]
 [0.0 1.0 0.0 0.5219936576146885 -0.23749170229683292]
 [1.0 0.0 0.0 1.8260075532171811 -0.11941792468654079]
 [0.0 0.0 1.0 -1.1080237118884273 -0.9330208099450786]
 [1.0 0.0 0.0 0.9566649561488527 -0.6334912379085142]]


In [233]:
print(X_test)

[[0.0 0.0 1.0 -1.1080237118884273 -0.9531627117523096]
 [1.0 0.0 0.0 -1.4340271857890505 -1.4217543112160194]]
